version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - redis_data:/data
    networks:
      - text-analyzer-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongodb_data:/data/db
    networks:
      - text-analyzer-network
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - '5000:8081' # Mongo-Express web UI port
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://root:1234@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - text-analyzer-network
    restart: unless-stopped
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=dev-file
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm.json
    command: ['start-dev', '--import-realm']
    ports:
      - '8080:8080'
    volumes:
      - ./keycloak-realm.json:/opt/keycloak/data/import/realm.json
    networks:
      - text-analyzer-network
  text-analyzer-api:
    container_name: text-analyzer-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=mongodb://root:1234@mongodb:27017/text-analizer?directConnection=true&authSource=admin&retryWrites=true
      - REDIS_URL=redis://redis:6379
      - KEYCLOAK_ISSUER=http://keycloak:8080/realms/text-analyzer
      - KEYCLOAK_CLIENT_ID=nestjs-oauth-client
    depends_on:
      - redis
      - mongodb
      - keycloak
    restart: unless-stopped
    networks:
      - text-analyzer-network
volumes:
  redis_data:
    driver: local
  mongodb_data:
    driver: local
  grafana-data:
    driver: local
networks:
  text-analyzer-network:
    driver: bridge
